services:
  budibase:
    image: budibase/budibase:latest
    restart: unless-stopped
    env_file:
      - /opt/streamline/config/.env
    environment:
      - BB_ADMIN_EMAIL=${PORTAL_BUDIBASE_ADMIN_EMAIL:-admin@local}
      - BB_ADMIN_PASSWORD=${PORTAL_BUDIBASE_ADMIN_PASSWORD:-ChangeMe_123!}
      - REDIS_PASSWORD=${PORTAL_BUDIBASE_REDIS_PASSWORD}
      - JWT_SECRET=${PORTAL_BUDIBASE_JWT_SECRET}
    volumes:
      - /opt/streamline/data/budibase:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"

      # HTTPS router (use detected entrypoint)
      - "traefik.http.routers.budibase.rule=Host(`portal.streamline-internal.com`)"
      - "traefik.http.routers.budibase.entrypoints=websecure"
      - "traefik.http.routers.budibase.tls=true"

      # HTTP router -> redirect to HTTPS (use detected entrypoint)
      - "traefik.http.routers.budibase-http.rule=Host(`portal.streamline-internal.com`)"
      - "traefik.http.routers.budibase-http.entrypoints=web"
      - "traefik.http.routers.budibase-http.middlewares=budibase-redirect"
      - "traefik.http.middlewares.budibase-redirect.redirectscheme.scheme=https"

      # Service port (internal)
      - "traefik.http.services.budibase.loadbalancer.server.port=${PORTAL_BUDIBASE_INTERNAL_PORT}"

      # Force Traefik to use this docker network
      - "traefik.docker.network=web"

networks:
  web:
    external: true
