entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

log:
  level: INFO
accessLog: {}

providers:
  docker:
    exposedByDefault: false
    network: web
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
